

name: First Github Actions Workflow

on: 
  workflow_dispatch:

jobs:
  
  Welcome:

    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "Welcome to Github Actions!"

